"""Doctor portal authentication — login, forced password change, refresh, logout.

Portal URL: /doctor/auth/*
Doctors log in with email + password (email auto-generated by admin on account creation).
Must change password on first login (must_change_password flag).
Blocked immediately if DoctorProfile.is_active = False.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, Response, status
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.dependencies import get_client_ip
from app.core.security import (
    create_access_token,
    create_refresh_token,
    hash_password,
    verify_password,
    set_refresh_cookie,
    clear_refresh_cookie,
    decode_access_token,
)
from app.models.audit_log import AuditLog, AuditEventType
from app.models.doctor_profile import DoctorProfile
from app.models.user import User, UserRole

router = APIRouter(prefix="/doctor/auth", tags=["Doctor Auth"])


class DoctorLoginRequest(BaseModel):
    email: str   # accepts email OR medical registration number (e.g. MRN-12345678)
    password: str


class DoctorChangePasswordRequest(BaseModel):
    current_password: str
    new_password: str = Field(..., min_length=8, description="Minimum 8 characters")


async def _audit(db: AsyncSession, event_type: str, user: User, description: str, ip: str, metadata: dict = None):
    db.add(AuditLog(
        id=uuid.uuid4(),
        user_id=user.id,
        actor_id=user.id,
        event_type=event_type,
        description=description,
        metadata_json=metadata or {},
        ip_address=ip,
    ))


@router.post("/login", summary="Doctor portal login (email + password)")
async def doctor_login(
    body: DoctorLoginRequest,
    response: Response,
    db: AsyncSession = Depends(get_db),
    ip: str = Depends(get_client_ip),
):
    """
    Doctor login. Uses email (auto-generated by admin) + password.
    Two-layer block:
    1. User.is_active — account not suspended
    2. DoctorProfile.is_active — clinical profile activated by admin
    Force password change if must_change_password=True.
    """
    login_id = body.email.strip()  # can be email or MRN

    user: User | None = None
    # Try lookup by MRN first (e.g. user typed "MRN-82597077")
    if login_id.upper().startswith("MRN-") or login_id.isdigit():
        profile_result = await db.execute(
            select(DoctorProfile).where(DoctorProfile.medical_reg_number == login_id.upper())
        )
        profile_lookup = profile_result.scalar_one_or_none()
        if profile_lookup:
            user_result = await db.execute(
                select(User).where(User.id == profile_lookup.user_id, User.role == UserRole.DOCTOR)
            )
            user = user_result.scalar_one_or_none()

    # Fall back to email lookup
    if user is None:
        user_result = await db.execute(
            select(User).where(User.email == login_id, User.role == UserRole.DOCTOR)
        )
        user = user_result.scalar_one_or_none()

    if not user or not verify_password(body.password, user.password_hash):
        db.add(AuditLog(
            id=uuid.uuid4(),
            event_type=AuditEventType.LOGIN_FAILED.value,
            description=f"Doctor login failed: {login_id[:50]}",
            ip_address=ip,
        ))
        await db.commit()
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid credentials",
        )

    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Account is deactivated. Contact administrator.",
        )

    # Check DoctorProfile.is_active
    profile_result = await db.execute(
        select(DoctorProfile).where(DoctorProfile.user_id == user.id)
    )
    profile = profile_result.scalar_one_or_none()
    if not profile or not profile.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Doctor account is not yet activated. Contact administrator.",
        )

    now = datetime.now(timezone.utc)
    user.last_login_at = now
    user.last_login_ip = ip
    user.failed_login_attempts = 0

    access_token = create_access_token(str(user.id), "DOCTOR", token_version=user.token_version or 0)
    refresh_token = create_refresh_token(str(user.id))
    user.refresh_token_hash = hash_password(refresh_token[:72])

    await _audit(db, AuditEventType.DOCTOR_LOGIN_SUCCESS.value, user, "Doctor login successful", ip)
    await db.commit()

    set_refresh_cookie(response, refresh_token)

    return {
        "access_token": access_token,
        "token_type": "bearer",
        "must_change_password": user.must_change_password,
        "doctor": {
            "id": str(user.id),
            "full_name": user.full_name,
            "email": user.email,
            "medical_reg_number": profile.medical_reg_number,
            "hospital_name": profile.hospital_name,
            "specialization": profile.specialization,
        },
    }


@router.post("/change-password", summary="Doctor forced password change (first login)")
async def change_password(
    body: DoctorChangePasswordRequest,
    request: Request,
    db: AsyncSession = Depends(get_db),
    ip: str = Depends(get_client_ip),
):
    """Change doctor password. Can be called with the existing access token."""
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing token")

    token = auth_header[7:]
    payload = decode_access_token(token)
    result = await db.execute(
        select(User).where(User.id == payload["sub"], User.role == UserRole.DOCTOR)
    )
    user = result.scalar_one_or_none()
    if not user:
        raise HTTPException(status_code=401, detail="Unauthorized")

    if not verify_password(body.current_password, user.password_hash):
        raise HTTPException(status_code=400, detail="Current password is incorrect")

    if body.new_password == body.current_password:
        raise HTTPException(status_code=400, detail="New password must differ from current")

    user.password_hash = hash_password(body.new_password)
    user.must_change_password = False
    user.token_version = (user.token_version or 0) + 1
    await _audit(db, AuditEventType.PROFILE_UPDATED.value, user, "Doctor password changed", ip)
    await db.commit()

    return {"message": "Password changed successfully. Please log in again with your new password."}


@router.post("/logout", summary="Doctor logout")
async def logout(
    request: Request,
    response: Response,
    db: AsyncSession = Depends(get_db),
    ip: str = Depends(get_client_ip),
):
    auth_header = request.headers.get("Authorization", "")
    if auth_header.startswith("Bearer "):
        try:
            token = auth_header[7:]
            payload = decode_access_token(token)
            result = await db.execute(select(User).where(User.id == payload["sub"]))
            user = result.scalar_one_or_none()
            if user:
                user.refresh_token_hash = None
                await _audit(db, AuditEventType.LOGOUT.value, user, "Doctor logged out", ip)
                await db.commit()
        except Exception:
            pass
    clear_refresh_cookie(response)
    return {"message": "Logged out successfully"}
